# -*- coding: utf-8 -*-
"""re2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pSallhoESzkr9A2x8cqIqChIpwuKwqBX
"""

import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import string
import re

nltk.download('punkt')
nltk.download('stopwords')

# Load dataset
data = pd.read_csv('/content/drive/MyDrive/project-re/project (2).csv')

# Sample of the dataset
print("Original Dataset:")
print(data.head())

# Function for text preprocessing
def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Tokenization
    tokens = word_tokenize(text)
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    # Stemming
    porter = PorterStemmer()
    stemmed_tokens = [porter.stem(word) for word in filtered_tokens]
    # Normalization - Convert numbers to a placeholder token
    normalized_text = [re.sub(r'\b\d+\b', '__NUMBER__', word) for word in stemmed_tokens]
    return ' '.join(normalized_text)

# Apply preprocessing to the 'text' column
data['clean_text'] = data['Review'].apply(preprocess_text)

# Display preprocessed dataset
print("\nPreprocessed Dataset:")
print(data[['Review', 'clean_text']].head(20))

